# ----Basic Numpy----

In [2]:
import numpy as np


In [ ]:
a = np.array([1,2,3,4]) ##Create array // dtype is used to indicate type in array
a.dtype ##Check type in array
a[x:y:z] ##Get value start x stop y step z

In [ ]:
a.shape ##Show length of all dimension
a.ndim ##Show dimension

In [19]:
np.arange(4) ##Create array from 0 to 3
np.random.randint(100,size=(3,3)) ##Random int 0-100 // with shape 3*3

array([[88, 93, 32],
       [37, 39,  1],
       [55, 17, 48]])

# Stat

In [ ]:
a.sum()
a.mean()
a.std()
a.var()

In [ ]:
a.sum(axis=0) ##Sum of each row
a.sum(axis=1) ##Sum of each column

# Boolean arrays

In [16]:
a=np.arange(4)

In [14]:
a[a >= 2]

array([2, 3])

In [20]:
a[(a == 0) | (a ==1)] ## Or condition
a[(a == 0) & (a ==1)] ## And condition
a[~(a == 0)] ## Not condition

array([1, 2, 3])

In [17]:
a

array([0, 1, 2, 3])

# ----PANDAS----

In [2]:
import pandas as pd

In [10]:
pop = pd.Series([35,20,53,24,90], index = ['Canada','USA','Thai','China','Japan']) ##Different from list is that we can assign index
pop

Canada    35
USA       20
Thai      53
China     24
Japan     90
dtype: int64

In [13]:
pop.loc[['Thai','USA']]

Thai    53
USA     20
dtype: int64

In [15]:
pop.iloc[1]

USA    20
dtype: int64

In [21]:
pop > pop.mean()


Thai     53
Japan    90
dtype: int64

In [28]:
pop[(pop > pop.mean()) | (pop < 21)]

USA      20
Thai     53
Japan    90
dtype: int64

# Dataframe

In [3]:
df = pd.read_csv( 
    'data/btc-market-price.csv', 
    header = None, 
    names = ['date','price'],
    index_col = 0,
    parse_dates = True, 
    ) ##
df = pd.read_csv('data/btc-market-price.csv', header = None)
df.columns = ['date','price']

In [ ]:
df.info() ##Dataframe overview
df.describe() ##Summary of satistic of Dataframe
df.dtypes()
df[x,y] ##x = index / y = column
df.rename(columns = {'old':'new','old2':'new2'}, index = {'old3','new3'}) ##rename index and columns

In [38]:
df.head() ##Get head
df.tail() ##Get tail

<bound method NDFrame.head of                        0                   1
0                   date               price
1    2017-04-02 00:00:00         1099.169125
2    2017-04-03 00:00:00            1141.813
3    2017-04-04 00:00:00        1141.6003625
4    2017-04-05 00:00:00  1133.0793142857142
..                   ...                 ...
361  2018-03-28 00:00:00             7960.38
362  2018-03-29 00:00:00             7172.28
363  2018-03-30 00:00:00   6882.531666666667
364  2018-03-31 00:00:00             6935.48
365  2018-04-01 00:00:00            6794.105

[366 rows x 2 columns]>

In [49]:
df['date'] =pd.to_datetime(df['date']) ##Change to date type

In [54]:
df.set_index('date', inplace = True) ##Replace index with specify column

KeyError: "None of ['date'] are in the columns"

In [56]:
df.loc['2017-04-02']

price    1099.169125
Name: 2017-04-02 00:00:00, dtype: float64